# Generated by Django 5.1.6 on 2025-03-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(max_length=150)),
                ('phylum', models.CharField(max_length=150)),
                ('class_name', models.CharField(max_length=150)),
                ('order', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('genus', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classification')),
            ],
        ),
    ]
