# Generated by Django 5.1.6 on 2025-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='alternativeNames',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organism',
            name='occurrenceStatusVerbatim',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organism',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
