# Generated by Django 5.1.6 on 2025-03-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organism_alternativenames_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='alternativeNames',
            new_name='alternative_names',
        ),
        migrations.RenameField(
            model_name='organism',
            old_name='occurrenceStatusVerbatim',
            new_name='occurrence_status_verbatim',
        ),
    ]
