# Generated by Django 5.2 on 2025-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_alternativenames_organism_alternative_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
