# Generated by Django 5.2 on 2025-04-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organism_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
