# Generated by Django 5.2 on 2025-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_organism_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('class_name', models.JSONField(blank=True, default=list)),
                ('order', models.JSONField(blank=True, default=list)),
                ('family', models.JSONField(blank=True, default=list)),
                ('genus', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
