# Generated by Django 5.2 on 2025-04-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_length',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
