# Generated by Django 5.2 on 2025-05-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quiz_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
