# Generated by Django 5.2 on 2025-05-01 19:40

from django.db import migrations, models

def create_initial_category_and_layer(apps, schema_editor):
    QuizCategory = apps.get_model('api', 'QuizCategory')
    QuizLayer = apps.get_model('api', 'QuizLayer')

    category = QuizCategory.objects.create(name='Default Category')
    QuizLayer.objects.create(category=category, level=0)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quiz_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='The depth level of the layer in this category')),
                ('category', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='layers', to='api.quizcategory')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('category', 'level')},
            },
        ),
        migrations.RunPython(create_initial_category_and_layer),
    ]