# Generated by Django 5.2 on 2025-05-01 19:41

from django.db import migrations, models


def assign_default_layer(apps, schema_editor):
    Quiz = apps.get_model('api', 'Quiz')
    QuizLayer = apps.get_model('api', 'QuizLayer')
    default_layer = QuizLayer.objects.first()
    for quiz in Quiz.objects.all():
        quiz.layer = default_layer
        quiz.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20250501_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='layer',
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name='quizzes',
                to='api.quizlayer'
            ),
        ),
        migrations.RunPython(assign_default_layer),
        migrations.AlterField(
            model_name='quiz',
            name='layer',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='quizzes',
                to='api.quizlayer'
            ),
        ),
    ]
