# Generated by Django 5.2 on 2025-05-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
    ]
