# Generated by Django 5.2 on 2025-05-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_quiz_required_attempts_userquizprogress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizCategory',
            new_name='QuizSubCategory',
        ),
        migrations.RenameField(
            model_name='quizlayer',
            old_name='category',
            new_name='sub_category',
        ),
        migrations.AlterUniqueTogether(
            name='quizlayer',
            unique_together={('sub_category', 'level')},
        ),
    ]
