# Generated by Django 5.2 on 2025-05-04 10:24

from django.db import migrations


def set_default_quiz_category(apps, schema_editor):
    QuizCategory = apps.get_model("api", "QuizCategory")
    QuizSubCategory = apps.get_model("api", "QuizSubCategory")
    
    # Create or get the default category; you can change "Default" to any default name you want.
    default_category, created = QuizCategory.objects.get_or_create(name="Default")
    
    # For every QuizSubCategory with a null category, assign the default category.
    for subcat in QuizSubCategory.objects.filter(category__isnull=True):
        subcat.category = default_category
        subcat.save()

def reverse_set_default_quiz_category(apps, schema_editor):
    # Optionally, you can leave reverse as a no-op, or set category back to null.
    QuizSubCategory = apps.get_model("your_app_name", "QuizSubCategory")
    for subcat in QuizSubCategory.objects.all():
        subcat.category = None
        subcat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_quizcategory_quizsubcategory_category'),
    ]

    operations = [
        migrations.RunPython(set_default_quiz_category, reverse_code=reverse_set_default_quiz_category),
    ]