# Generated by Django 5.2 on 2025-05-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20250504_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.quizcategory'),
        ),
    ]
