# Generated by Django 5.2 on 2025-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_quizsubcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlayer',
            name='level',
            field=models.PositiveIntegerField(help_text='The depth level of the layer in this subcategory'),
        ),
    ]
