# Generated by Django 5.2 on 2025-05-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_quizlayer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsubcategory',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
