# Generated by Django 5.2 on 2025-05-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_quizcategory_image_url_quizsubcategory_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='class_name',
            new_name='class_names',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='family',
            new_name='families',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='genus',
            new_name='genera',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='order',
            new_name='orders',
        ),
    ]
