# Generated by Django 5.2 on 2025-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_quizcategory_class_names_quizcategory_families_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlayer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
