# Generated by Django 5.2 on 2025-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_quiz_image_url_alter_quizcategory_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='image_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organism',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
