# Generated by Django 5.2 on 2025-05-08 17:54

from django.db import migrations

def migrate_image_url_to_image_urls(apps, schema_editor):
    Organism = apps.get_model('api', 'Organism')
    for organism in Organism.objects.all():
        if organism.image_url:
            organism.image_urls = [organism.image_url]
            organism.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_organism_image_urls_organism_is_verified'),
    ]

    operations = [
        migrations.RunPython(migrate_image_url_to_image_urls),
    ]

