# Generated by Django 5.2 on 2025-05-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_migrate_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism',
            name='image_url',
        ),
    ]
